mongodb:
  host: localhost
  port: 27017
cache_dir:

available_datasets:
  - Openarms
  - MENA_Agressions
  - MENA_Ajudes
  - Andalucia_2022
  - Generalitat_2021
  - Generales_2019
  - Barcelona_2019

reference_types:
  - retweeted
  - quoted
  - replied_to
theme: PULSE
debug: False
textual:
  api_url: 'http://srvinv02.esade.es:5005/api'
profiling:
  data_dir: './profiling_data/'
multimodal:
  data_dir: './multimodal_data/'
wordcloud:
  max_words: 15
  width: 400
  height: 400
  match_width: True
tweet_table:
  page_size: 10
cut_bins:
  - Low
  - Medium
  - High
propagation:
  max_edges:
    hidden_network: 4000
    propagation_tree: 1000
  graph_layout: fruchterman_reingold
  frequency: 1D

anonymous: True
