mongodb:
  host: localhost
  port: 27017
cache_dir:

available_datasets:
  - test_dataset_2
  - test_dataset_3
reference_types:
  - retweeted
  - quoted
  - replied_to
theme: PULSE
debug: True

textual:
  api_url: 'http://srvinv02.esade.es:5005/api'
profiling:
  data_dir: './profiling_data/'
multimodal:
  data_dir: './multimodal_data/'
wordcloud:
  max_words: 15
  width: 400
  height: 400
  match_width: True
tweet_table:
  page_size: 10
cut_bins:
  - Low
  - Medium
  - High
propagation:
  max_edges: 1000
  graph_layout: fruchterman_reingold
  threshold: 0.3
  frequency: 1D