mongodb:
  host: localhost
  port: 27017
  database: remiss
cache_dir:
graph_layout: fruchterman_reingold
graph_simplification:
  method: backbone
  threshold: 0.95
available_datasets:
theme: PULSE
debug: True
frequency: 1D
prepopulate: False
uv:
  api_url: 'http://agentsim.uv.es:5000/api'