mongodb:
  host: localhost
  port: 27017
cache_dir:
graph_layout: fruchterman_reingold
graph_simplification:
  method: backbone
  threshold: 0.95
available_datasets:
theme: PULSE
debug: True
frequency: 1D
uv:
  api_url: 'http://srvinv02.esade.es:5005/api'