mongodb:
  host: localhost
  port: 27017
cache_dir: /shared/remiss/data/Twitter/.cache/
graph_layout: fruchterman_reingold
graph_simplification:
  method: backbone
  threshold: 0.95
available_datasets:
theme: PULSE
debug: "True"
frequency: 1D